### ISSUE TITLE
Build instructions

### ISSUE THREAD

**Issue by mureinik** [xandradx/ovirt-engine-disaster-recovery#2]
Could you please add instructions on how to build the project locally from source to README.md?

**Comment by xandradx** [comment]
I have a working RPM, and SRPMs.

I could add them.

Will that be ok ?

**Comment by mureinik** [comment]
What I'm missing is, e.g., instructions on how to create these RPMs. How's a developer that wants to contribute to this project supposed to test his contributions?

**Comment by mrlpm** [comment]
I added instructions for install from source 
https://github.com/xandradx/ovirt-engine-disaster-recovery#installing-ovirt-engine-disaster-recovery-from-source
